### ISSUE TITLE
click.mydomain.com does not work

### ISSUE THREAD

**Issue by infooer** [atech/postal#215]
I configure Click & Open Tracking according to the configuration instructions，but it does't work, 
tcp        0      0 127.0.0.1:5000          0.0.0.0:*               LISTEN      32132/[postal] web.
tcp        0      0 0.0.0.0:25672           0.0.0.0:*               LISTEN      16907/beam.smp
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN      17878/mysqld
tcp        0      0 43.249.11.146:80        0.0.0.0:*               LISTEN      39204/nginx -g daem
tcp        0      0 0.0.0.0:4369            0.0.0.0:*               LISTEN      16986/epmd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      990/sshd
tcp        0      0 43.249.11.146:443       0.0.0.0:*               LISTEN      39204/nginx -g daem
tcp6       0      0 :::5672                 :::*                    LISTEN      16907/beam.smp
tcp6       0      0 :::4369                 :::*                    LISTEN      16986/epmd
tcp6       0      0 :::22                   :::*                    LISTEN      990/sshd
tcp6       0      0 :::25                   :::*                    LISTEN      62596/[postal] smtp
i think its because the web server didn't listen at 5010 and 5011 ,but i don't know how to fix it,can you help me?

**Comment by willpower232** [comment]
have you enabled it in postal.yml? I have a section at the top which looks like this:

```
fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address: 172.31.25.250
```
