### ISSUE TITLE
Can't get emails from Postal admin

### ISSUE THREAD

**Issue by theratris** [atech/postal#43]
I am currently locked out of my admin account because I changed the settings. Now it requires the 6-digit code to resume panel use. I have configured the SMTP settings and could send test mail fine, but I can't get the Postal admin panel to send me emails itself.

From postal.yml:
```
smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: mail.iPutMyDomainHere.com
  port: 2525
  username: iPutMyUsernameHere
  password: iPutMyPasswordHere
  from_name: Postal
  from_address: postal@forum.betterbot.org
```
