### ISSUE TITLE
Add the ability to change the SMTP SSL certificate

### ISSUE THREAD

**Issue by deanpcmad** [atech/postal#45]
I'm using Lets Encrypy for the HTTPS SSL cert so I'd also like to use that for the SMTP cert as it currntly seems to be using the one in `config/smtp.cert` & `config/smtp.key`.

Would it be possible to change this to a config variable where I can point it to my Lets Encrypt key location?

This may also be linked to #39, #43 & #44

**Comment by xoco70** [comment]
and [#40](https://github.com/atech/postal/issues/40)

**Comment by jduncanator** [comment]
Above PR should resolve the issue as well as #39, #40, #43 and #44.

**Comment by adamcooke** [comment]
This is now complete. You can set the path to the SMTP certificates/key using:

```yaml
smtp_server:
  tls_certificate_path: /path/to/cert
  tls_private_key_path: /path/to/key
```
