### ISSUE TITLE
Bind SMTP server to IPv4 only?

### ISSUE THREAD

**Issue by tankerkiller125** [atech/postal#585]
The problem that I have right now is that the SMTP server is only binding to port 25 on IPv6 which is a major issue because my network only supports IPv6. I have attempted completely disabling IPv6 on the server itself and ensured that the router isn't handing out IPv6 or anything weird like that. In the end my network interfaces have NO ipv6 addresses at all.

My current config:
```yaml
web:
  # The host that the management interface will be available on
  host: postal.demo.tld
  # The protocol that requests to the management interface should happen on
  protocol: http

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: false
  bind_address:

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false
  exception_url: http://dns
main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: secret
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: secret
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: secret
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mx.postal.demo.tld
  smtp_server_hostname: postal.demo.tld
  spf_include: spf.postal.demo.tld
  return_path: rp.postal.demo.tld
  route_domain: routes.postal.demo.tld
  track_domain: track.postal.demo.tld

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 25
  username: demo\live # Complete when Postal is running and you can
  password: secret # generate the credentials within the interface.
  from_name: Postal Server
  from_address: postal@demo.tld

spamd:
  enabled: true
  host: 127.0.0.1
  port: 783

clamav:
  enabled: true
  host: 192.168.86.129
  port: 3310

smtp_server:
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/demo.tld/fullchain.pem
  tls_private_key_path: /etc/letsencrypt/live/demo.tld/privkey.pem
  ssl_version: TLSv1_1
  tls_ciphers: TLSv1_1
```
