### ISSUE TITLE
Can't verify domain: [WARNING: No SPF record exists for this domain]

### ISSUE THREAD

**Issue by shinebayar-g** [atech/postal#623]
Hello postal team.
First of all, thanks for making such great project. Unfortunately I'm having hard time setting this up.
I tried to solve this problem all myself without opening issue, but It seems I can't get it working without help.

I've successfully installed the postal project and everything runs fine. I created my first organization and first server. Went to **Domains** and added my first domain. Followed the instruction as it said, but I can't verify **SPF Record** part.

Here is my `postal.yml` file. I removed unrelated parts.

```YAML
web:
  # The host that the management interface will be available on
  host: postal.mydomain.io
  # The protocol that requests to the management interface should happen on
  protocol: https

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - postal.mydomain.io
  smtp_server_hostname: postal.mydomain.io
  spf_include: spf.postal.mydomain.io
  return_path: rp.postal.mydomain.io
  route_domain: routes.postal.mydomain.io
  track_domain: track.postal.mydomain.io
  helo_hostname: # By default, this will be the same as the `smtp_server_hostname`
  dkim_identifier: postal
  domain_verify_prefix: postal-verification
  custom_return_path_prefix: psrp

smtp_server:
  port: 2525
  tls_enabled: false
  tls_certificate_path: # Defaults to config/smtp.cert
  tls_private_key_path: # Defaults to config/smtp.key
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false

smtp_relays:
  -
    hostname:
    port: 2525
    ssl_mode: Auto

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: postal.mydomain.io
  port: 2525
  username: myfirst-stmp # Complete when Postal is running and you can
  password: HvVmXCJeeqeZdyVvGc3bmvb7I # generate the credentials within the interface.
  from_name: Postal
  from_address: noreply@postal.mydomain.io
```

My DNS entries:

```
A | postal | points to MyVpsStaticIP
CNAME | psrp.postal | is an alias of rp.postal.mydomain.io
MX | postal | mail handled by postal.mydomain.io (10)
TXT | postal-cayfef._domainkey.postal | v=DKIM1; t=s; h=sha256; p=MIGfMA0GCSqGSIb3DQEB...
TXT | mydomain.io | v=spf1 include:servers.mcsv.net include:spf.postal.mydomain.io ?all
```

About last record, there was an existing TXT record on my root domain **mydomain.io**. So I added **include:spf.postal.mydomain.io** to existing record as Dns setup page suggested. Since it didn't work I even removed existing record and added new entry for `domain root: @` `v=spf1 a mx include:spf.postal.mydomain.io ~all`

I've tried to send test email, but it seems I cannot send emails until I verify the domain. It says SOFT FAIL.
