### ISSUE TITLE
Clam AV

### ISSUE THREAD

**Issue by blakilox** [atech/postal#639]
https://github.com/atech/postal/wiki/Spam-&-Virus-Checking
was a great help Thank you and I set up Spamassassin though how to setup CLAM?

First steps I guess
sudo apt install clamav clamav-daemon clamsmtp
add CRON 
00 01 * * * root /usr/share/clamav/freshclam-sleep

though how to get POSTAL to talk to the CLAM?

**Comment by igerzog** [comment]
You should add this code to your `postal.yml`config file:
```
clamav:
  enabled: true
  host: 127.0.0.1
  port: 785 # port can be changed to preferred
```
