### ISSUE TITLE
Can't use Let's Encrypt certificate for SMTP server.

### ISSUE THREAD

**Issue by shinebayar-g** [atech/postal#665]
I'm using Let's Encrypt's SSL. Website is working fine with HTTPS. But If I try to use those certificates in SMTP server I'm getting this error.  When I test SMTP settings with `postal test-app-smtp myemailaddress@gmail.com` it gives following:
```
Error: OpenSSL::SSL::SSLError (SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A)

or

Error: Errno::ECONNRESET (Connection reset by peer - SSL_connect)
```

Here is related config from postal.yml
```YAML
smtp_server:
  port: 2525
  tls_enabled: true
  tls_certificate_path: /etc/letsencrypt/live/postal.mydomain.com/fullchain.pem # I used chown -R postal:postal /etc/letsencrypt/live/postal.mydomain.com to ensure permission
  tls_private_key_path: /etc/letsencrypt/live/postal.mydomain.com/privkey.pem
  proxy_protocol: false
  log_connect: true
  strip_received_headers: false
```
If I disable tls, email is sending fine. But that means emails are sending in plain text right?
I've googled a lot and tried to add these lines into SMTP settings.
```YAML
  tls_ciphers:
  ssl_version: TLSv1
```
Also tried to change tls_ciphers, ssl_version into many different combinations no luck. I assume postal is not recognizing the value of ssl_version.
