### ISSUE TITLE
harmony with other services

### ISSUE THREAD

**Issue by epipheus** [atech/postal#856]
I have tried to get postal to live in harmony with GSuite.  I have setup Postal's base to be a clean domain I don't do anything else with.  But in the system I've added a domain that also uses Gmail as the primary email, (I didn't see an issue, after all I do this for mailgun and others).  Presently, Postal isn't sending messages for me and the only complaint I see in the logs is the below:

- `Cannot connect to 173.194.68.27:25 (aspmx.l.google.com) (Net::OpenTimeout: execution expired)` for each google MX
- Also `No SMTP server available for xxxxx.com`, where xxxxx.com is the domain of a test recipient I sent a test message to through Postal

So my questions are:

- Why doesn't Postal ignore irrelevant MX's? I think It's possible my new MX simply wasn't propagated and Postal didn't see a relevant MX and so tried all the Google MX's.  But the system indicated it could in fact see the MX, but it isn't using it which is perplexing.  Wouldn't continuous attempt to connect endanger the Postal base IP getting flagged?
- It doesn't make sense to me at all which it is searching for an SMTP server for xxxxx.com. Unless the error is to indicate that there isn't any SMTP server properly setup in itself to send a message to person1@xxxxx.com.  In that case, I would say that the message is very unclear.

**Comment by epipheus** [comment]
is there a way to see what MX's it can see? Other than the ui showing that the domain is setup, is there a command to spit out a zone file snippet of what it can see?

**Comment by willpower232** [comment]
You should be able to install and run `dig` on the server running Postal to see what records it can see. You can also use whatsmydns.net to check the propagation of records around the world.

If you send a message for a domain, it will look up the MX records and act on what it receives. If your server doesn't have the latest information, theres not a lot that can be done but wait.

**Comment by epipheus** [comment]
so look up happens at event time, makes sense.  yeah I used dig from the machine and it wasn't consistent.  I will wait.  However, I still need to understand the errors -- Postal knows that the Google MXs are irrelevant, because they don't match endpoints in postal.yml; so why attempt connecting to them at all? I would assume there should be an error that looks like `"Postal does not see MX endpoints matching mail.yourdomain.com. Please configure DNS appropriately or wait for propagation"`

**Comment by willpower232** [comment]
> because they don't match endpoints in postal.yml

Postals job is to communicate with the internet, or at least according to the DNS it can see. In theory, most messages going through a Postal server would be to all sorts of domain names so second guessing itself every time it sent a message would be a waste of time.

Its possible that some errors could be better worded but it should be rare that the operator of the Postal server can do anything about their recipients email setups so other than "your email address is broken", the basic information is available.

**Comment by catphish** [comment]
I'm not sure I fully understand the questions here. Firstly, it appears that your server cannot connect to Google's MX servers with a timeout error. I would assume that this error is being caused by your ISP not allowing outbound SMTP connections.

Secondly, you imply that you are not expecting Postal to connect to Google's SMTP servers at all. **Why are you not expecting this?** Postal will always send emails to MX servers as specified in DNS. The only exception is if you are using an SMTP relay (as specified under `smtp_relays`).

**Comment by epipheus** [comment]
I've specified a subdomain for Postal, why would it ignore that and try sending mail to root domain MXs?  At present, I also have mailgun, sendgrid and pandadoc MXs, all of which are smart enough to only use the relevant portions of DNS and not just the first MX it finds!  So @catfish, I'm not expecting this because it is unexpected -- it's not how other similar products work; and I don’t believe this is uncommon for decent size businesses. 

Among many things, Pandadoc sends documents that need signatures for our organization; it has it’s own security processes but uses mailgun underneath.  I’m hoping to use Postal instead of mailgun and sendgrid and obviously, our GSuite servers are for employee mail.  What is the purpose of `postal.yml` if you’re just going to connect to any MXs you find in DNS?  Why have any of the instructions in [your domain instructions](https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration) if you’ll use any MXs at the root?  Sub-domains matter. You should only be using the MXs from your aforementioned doc link. 

Like many businesses we need to differentiate between mail sent through applications versus individual employees.  And @catphish shouldn’t it be my choice what goes where?!  It's like the difference between an email address from corp.yahoo.com for employees of Yahoo versus the public yahoo.com email any Joe Bloke can have (for those of us old enough to remember Yahoo!).  Additionally, each kind of email has different security processes – ex: we have a great deal more security steps for business email, not the least of which is 2fa which makes a little bit less sense for application mail; also wouldn’t improper connections to GSuite MXs hurt deliverability? God forbid Google report to spam our own failed connections!

Lastly, `No SMTP Server available for xxxxx.com` just doesn’t make sense to me as a message; neither does `Your email address is broken` -- what does that mean? Did I get a bounce message?  Is the email address malformed?  How does that point me toward solving whatever the issue is?  I mean, that’s why we have error messages in the first place right? So that people can then determine what to do to fix them; so it isn’t a negligible point to discuss whether there is indeed better wording for error messages.  I’ve penned this issue because it doesn’t make sense to me.  If it did make sense to me all of us could perhaps save some time.  Every message you have that helps me not waste my time or your time is a good message.

**Comment by epipheus** [comment]
> Postals job is to communicate with the internet, or at least according to the DNS it can see. 

It is not just about anything you can see, I can see almost everything in a zone file for anyone's DNS configuration. It is about synthesizing what you see and doing something relevant. Connecting to an irrelevant server is not Postal’s job.

> In theory, most messages going through a Postal server would be to all sorts of domain names so second guessing itself every time it sent a message would be a waste of time.

So, we are talking about a couple things so let's disambiguate and if you really find it necessary I can split these out into separate issues.  

1. First issue is that you're connecting to the first set of MXs you see, ignoring a subdomain configured in postal.yml to do so. That is not expected behavior, it’s not how other production products of its kind work, nor should it be.  I believe you should only connect to MXs setup in the postal.yml configuration file.  And btw, this could be further disambiguated with details that the core application is on its own clean domain and this particular problem is with setting up a Mail Server in Postal’s application, just like someone setting up Mailgun would need to do.  The problem occurs in that context, but the basic situation is that you’re trying to connect to something you shouldn’t be connecting to. 

1. Second issue is that I’m getting a weird message `No SMTP server available for xxxxx.com`, where xxxxx.com is the domain of a test recipient I sent a test message to through Postal.  Why does a recipient’s SMTP server matter at the point of sending them a message?  In this context, Postal’s job is just to send, down the line if there is a bounce, OK, record that bounce and we can deal with that.  So what exactly does this mean? It should be clear. I’m not asking Postal to ‘second guess itself’ despite the fact that it *IS* second guessing itself.  I didn’t produce the message, you did! My question is *WHY* is it concerning itself with the SMTP server of the recipient as it sends a message.  I AGREE WITH YOU, second guessing itself is a waste of time.  I also think sending a message that doesn’t help me determine the real issue is also a waste of time!!!

**Comment by willpower232** [comment]
So one thing at a time...

> First issue is that you're connecting to the first set of MXs you see, ignoring a subdomain configured in postal.yml to do so. That is not expected behavior, it’s not how other production products of its kind work, nor should it be. I believe you should only connect to MXs setup in the postal.yml configuration file.

I don't believe thats how postal.yml works, can you share a slightly redacted copy of your postal.yml?

**Comment by catphish** [comment]
It's going to be difficult working with these redacted email addresses, as I can't verify your DNS configuration. However, what matters here is what MX records exist for the domain name you're trying to send email to?
You keep mentioning postal.yml, and I don't understand why. When Postal is sending email, it sends to servers defined by MX records for the domain in the destination email address. I don't see what postal.yml would have to do with this.
Can you clarify?

**Comment by catphish** [comment]
I think I'm starting to understand now.

> Why does a recipient’s SMTP server matter at the point of sending them a message?

That's literally how email works.

Are you instead expecting Postal to be using an intermediary relay server. If you are expecting this, have you defined such a relay server (under `smtp_relays`)?

**Comment by epipheus** [comment]
> That's literally how email works.

Hahahaa, umm :) Right!  OK, so`No SMTP server available for xxxxx.com` means Postal cannot see the recipient's server from the VPS for whatever reason, most likely some form of blocking (Despite DigitalOcean saying there is no block and that ufw and Cloud Firewall properly configured). *sigh*

 > Are you instead expecting Postal to be using an intermediary relay server

I don't think that's what I'm expecting.  I simply want Postal to function like MailGun or Sendgrid.  Why doesn't MailGun or Sendgrid or Pandadoc require anything more than the relevant mx's that point to them, spf and cname?  

@catphish : I have not specified/defined smtp_relays. I don't want Postal to work through another mail server, I've set it up to be the mailserver(s). 

Here's my redacted postal.yml.  From the below, I expect that mail will be sent through mail.ravennest.com, now according to your instructions YOu have us put in an MX from subdom.mydomain.tld pointing to mail.ravennest.com as described below in the redacted config.

```yaml
web:
  # The host that the management interface will be available on
  host: ravennest.com automatically by the config initialization. It should be a random
  # The protocol that requests to the management interface should happen on
  protocol: https

fast_server:
  # This can be enabled to enable click & open tracking on emails. It is disabled by
  # default as it requires a separate static IP address on your server.
  enabled: true
  bind_address:
    - 1234:a123:b123::blah:blah

general:
  # This can be changed to allow messages to be sent from multiple IP addresses
  use_ip_pools: false

main_db:
  # Specify the connection details for your MySQL database
  host: 127.0.0.1
  username: postal
  password: b3ndtheknee
  database: postal

message_db:
  # Specify the connection details for your MySQL server that will be house the
  # message databases for mail servers.
  host: 127.0.0.1
  username: postal
  password: b3ndtheknee
  prefix: postal

rabbitmq:
  # Specify the connection details for your RabbitMQ server.
  host: 127.0.0.1
  username: postal
  password: b3ndtheknee
  vhost: /postal

dns:
  # Specifies the DNS record that you have configured. Refer to the documentation at
  # https://github.com/atech/postal/wiki/Domains-&-DNS-Configuration for further
  # information about these.
  mx_records:
    - mail.ravennest.com
  smtp_server_hostname: mail.ravennest.com
  spf_include: spf.mail.ravennest.com
  return_path: rp.mail.ravennest.com
  route_domain: routes.mail.ravennest.com
  track_domain: track.mail.ravennest.com
  dkim_identifier: carrierraven
  domain_verify_prefix: raven-verification
  custom_return_path_prefix: ravenrp

smtp:
  # Specify an SMTP server that can be used to send messages from the Postal management
  # system to users. You can configure this to use a Postal mail server once the
  # your installation has been set up.
  host: 127.0.0.1
  port: 2525
  username: gameofthrones/westeros
  password: DracarysBlahblahIAeq2IC7LwhT
  from_name: Postal
  from_address: postal@raven.gameofthrones.tld

rails:
  # This is generated automatically by the config initialization. It should be a random
  # string unique to your installation.
  secret_key: blah0blah1blah2blah3blah4blah5blah0blah1blah2blah3blah4blah5blah0blah1blah2blah3blah4blah5blah0blah1blah2blah3blah4blah5
```
